[project]
name = "nanda-python-sdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "email-validator>=2.2.0",
    "httpx>=0.28.1",
    "pydantic>=2.11.3",
]
